"""add ballance

Revision ID: d98fc5117b5e
Revises: f51640d87d67
Create Date: 2023-06-10 10:34:27.603879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98fc5117b5e'
down_revision = 'f51640d87d67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('total_ballance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'total_ballance')
    # ### end Alembic commands ###
