"""unique blacklist

Revision ID: 4411f9309e61
Revises: d98fc5117b5e
Create Date: 2023-06-11 18:05:49.909154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4411f9309e61'
down_revision = 'd98fc5117b5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'black_list', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'black_list', type_='unique')
    # ### end Alembic commands ###
